# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ttop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ttop.proto',
  package='ttop_proto',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nttop.proto\x12\nttop_proto\"\x89\x02\n\x07TreeTop\x12&\n\x04tree\x18\x01 \x03(\x0b\x32\x18.ttop_proto.TreeTop.Tree\x1a\xd5\x01\n\x04Tree\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x18\n\x10\x63onsidered_chars\x18\x02 \x03(\t\x12\x12\n\nroot_chars\x18\x03 \x03(\t\x12+\n\x04root\x18\x04 \x02(\x0b\x32\x1d.ttop_proto.TreeTop.Tree.Node\x1a\x64\n\x04Node\x12\x0c\n\x04\x63har\x18\x01 \x02(\t\x12\r\n\x05\x64\x65pth\x18\x02 \x02(\x03\x12\x0e\n\x06visits\x18\x03 \x02(\x03\x12/\n\x08\x63hildren\x18\x04 \x03(\x0b\x32\x1d.ttop_proto.TreeTop.Tree.Node'
)




_TREETOP_TREE_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='ttop_proto.TreeTop.Tree.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='char', full_name='ttop_proto.TreeTop.Tree.Node.char', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth', full_name='ttop_proto.TreeTop.Tree.Node.depth', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visits', full_name='ttop_proto.TreeTop.Tree.Node.visits', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='children', full_name='ttop_proto.TreeTop.Tree.Node.children', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=292,
)

_TREETOP_TREE = _descriptor.Descriptor(
  name='Tree',
  full_name='ttop_proto.TreeTop.Tree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ttop_proto.TreeTop.Tree.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='considered_chars', full_name='ttop_proto.TreeTop.Tree.considered_chars', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root_chars', full_name='ttop_proto.TreeTop.Tree.root_chars', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root', full_name='ttop_proto.TreeTop.Tree.root', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TREETOP_TREE_NODE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=292,
)

_TREETOP = _descriptor.Descriptor(
  name='TreeTop',
  full_name='ttop_proto.TreeTop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tree', full_name='ttop_proto.TreeTop.tree', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TREETOP_TREE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=292,
)

_TREETOP_TREE_NODE.fields_by_name['children'].message_type = _TREETOP_TREE_NODE
_TREETOP_TREE_NODE.containing_type = _TREETOP_TREE
_TREETOP_TREE.fields_by_name['root'].message_type = _TREETOP_TREE_NODE
_TREETOP_TREE.containing_type = _TREETOP
_TREETOP.fields_by_name['tree'].message_type = _TREETOP_TREE
DESCRIPTOR.message_types_by_name['TreeTop'] = _TREETOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TreeTop = _reflection.GeneratedProtocolMessageType('TreeTop', (_message.Message,), {

  'Tree' : _reflection.GeneratedProtocolMessageType('Tree', (_message.Message,), {

    'Node' : _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
      'DESCRIPTOR' : _TREETOP_TREE_NODE,
      '__module__' : 'ttop_pb2'
      # @@protoc_insertion_point(class_scope:ttop_proto.TreeTop.Tree.Node)
      })
    ,
    'DESCRIPTOR' : _TREETOP_TREE,
    '__module__' : 'ttop_pb2'
    # @@protoc_insertion_point(class_scope:ttop_proto.TreeTop.Tree)
    })
  ,
  'DESCRIPTOR' : _TREETOP,
  '__module__' : 'ttop_pb2'
  # @@protoc_insertion_point(class_scope:ttop_proto.TreeTop)
  })
_sym_db.RegisterMessage(TreeTop)
_sym_db.RegisterMessage(TreeTop.Tree)
_sym_db.RegisterMessage(TreeTop.Tree.Node)


# @@protoc_insertion_point(module_scope)
